name: Build and Publish Docker Image

on:
  push:
    paths:
      - 'web/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.2.0
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and Push
        working-directory: ./web
        run: docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/jtumidanski/wedding-website/wedding-website-ui:latest --push .
